version: '3.9'

services:
  electric-checker-db:
    image: mysql:latest
    container_name: electric-checker-db
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mylocaldb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  electric-checker-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: electric-checker-app
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - USER=root
      - PASSWORD=mypassword
      - DATABASE=mylocaldb
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:mypassword@electric-checker-db:3306/mylocaldb
    depends_on:
      - electric-checker-db
    ports:
      - "8000:8000"
    restart: always

volumes:
  db_data:
