version: '3.9'

services:
  electric-checker-db:
    image: mysql:latest
    container_name: electric-checker-db
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mylocaldb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  electric-checker-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: electric-checker-app
    environment:
      - HOST=${HOST}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - ADMIN_KEY=${ADMIN_KEY}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    depends_on:
      - electric-checker-db
    ports:
      - "8000:8000"
    restart: always

volumes:
  db_data:
