version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "flask db upgrade &&
             gunicorn --workers 4 --bind 0.0.0.0:3003 wsgi:app"
    ports:
      - "3003:3003"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - ADMIN_KEY=${ADMIN_KEY}
      - HOST=${DB_HOST}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
      - DATABASE=${DB_NAME}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
